server:
  port: 8080

spring:
  application:
    name: scratch-data
  datasource:
    url: jdbc:mysql://localhost:3306/core_product
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver